#!/usr/bin/env python3
"""Run the VTA model comparison and residual analysis used in the manuscript.

The statistical formulas and output definitions are extracted from the actual
analysis script run_vta_lisbet_posthoc_conditionA_same_as_yours_fixed.py.
No synthetic or example data are generated by this script.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--long-csv",
        required=True,
        help="Restricted event-unit table created by 01_prepare_vta_event_unit_table.py",
    )
    parser.add_argument("--outdir", required=True, help="Directory for model outputs")
    args = parser.parse_args()

    long_csv = Path(args.long_csv).expanduser().resolve()
    outdir = Path(args.outdir).expanduser().resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    long_df = pd.read_csv(long_csv)
    required = {
        "trial_id", "unit_id", "prototype_id", "neural_z", "velocity_z", "distance_z"
    }
    missing = sorted(required - set(long_df.columns))
    if missing:
        raise ValueError(f"Missing required columns in {long_csv}: {missing}")

    long_df = long_df.dropna(subset=sorted(required)).copy()
    long_df["prototype_id"] = long_df["prototype_id"].astype(int)
    long_df["unit_id"] = long_df["unit_id"].astype(str)
    long_df["trial_id"] = long_df["trial_id"].astype(str)

    # Fixed unit effect controls for baseline differences between neurons/trials.
    # Model 1 tests simple metrics only.
    # Model 2 tests whether LISBET prototype ID adds information beyond simple metrics.
    formula_m1 = "neural_z ~ velocity_z + distance_z + C(unit_id)"
    formula_m2 = "neural_z ~ velocity_z + distance_z + C(prototype_id) + C(unit_id)"

    print("Fitting Model 1:", formula_m1)
    m1 = smf.ols(formula_m1, data=long_df).fit()

    print("Fitting Model 2:", formula_m2)
    m2 = smf.ols(formula_m2, data=long_df).fit()

    lr_stat, lr_p, df_diff = m2.compare_lr_test(m1)

    comparison = pd.DataFrame([{
        "n_observations": int(m2.nobs),
        "n_trials": int(long_df["trial_id"].nunique()),
        "n_units": int(long_df["unit_id"].nunique()),
        "n_prototypes": int(long_df["prototype_id"].nunique()),
        "model1_formula": formula_m1,
        "model2_formula": formula_m2,
        "model1_R2": m1.rsquared,
        "model2_R2": m2.rsquared,
        "delta_R2": m2.rsquared - m1.rsquared,
        "model1_adj_R2": m1.rsquared_adj,
        "model2_adj_R2": m2.rsquared_adj,
        "delta_adj_R2": m2.rsquared_adj - m1.rsquared_adj,
        "model1_AIC": m1.aic,
        "model2_AIC": m2.aic,
        "delta_AIC_model1_minus_model2": m1.aic - m2.aic,
        "model1_BIC": m1.bic,
        "model2_BIC": m2.bic,
        "delta_BIC_model1_minus_model2": m1.bic - m2.bic,
        "likelihood_ratio_stat": lr_stat,
        "likelihood_ratio_df": df_diff,
        "likelihood_ratio_p": lr_p,
    }])
    comparison.to_csv(outdir / "model_comparison_velocity_distance_vs_lisbet.csv", index=False)

    # Residual analysis from the original analysis script.
    long_df["neural_residual_after_velocity_distance"] = m1.resid
    formula_resid = "neural_residual_after_velocity_distance ~ C(prototype_id) + C(unit_id)"
    resid_model = smf.ols(formula_resid, data=long_df).fit()
    residual_null_formula = "neural_residual_after_velocity_distance ~ C(unit_id)"
    resid_null = smf.ols(residual_null_formula, data=long_df).fit()
    resid_lr, resid_p, resid_df = resid_model.compare_lr_test(resid_null)

    resid_comparison = pd.DataFrame([{
        "residual_model_formula": formula_resid,
        "residual_null_formula": residual_null_formula,
        "residual_null_R2": resid_null.rsquared,
        "residual_model_R2": resid_model.rsquared,
        "delta_residual_R2": resid_model.rsquared - resid_null.rsquared,
        "residual_null_AIC": resid_null.aic,
        "residual_model_AIC": resid_model.aic,
        "delta_AIC_null_minus_model": resid_null.aic - resid_model.aic,
        "residual_null_BIC": resid_null.bic,
        "residual_model_BIC": resid_model.bic,
        "delta_BIC_null_minus_model": resid_null.bic - resid_model.bic,
        "residual_likelihood_ratio_stat": resid_lr,
        "residual_likelihood_ratio_df": resid_df,
        "residual_likelihood_ratio_p": resid_p,
    }])
    resid_comparison.to_csv(outdir / "residual_analysis_lisbet_prototype.csv", index=False)

    resid_summary = (
        long_df.groupby("prototype_id", observed=True)
        .agg(
            n_observations=("neural_residual_after_velocity_distance", "size"),
            mean_residual=("neural_residual_after_velocity_distance", "mean"),
            median_residual=("neural_residual_after_velocity_distance", "median"),
            sem_residual=(
                "neural_residual_after_velocity_distance",
                lambda x: x.std(ddof=1) / np.sqrt(x.notna().sum()),
            ),
        )
        .reset_index()
    )
    resid_summary.to_csv(outdir / "residual_by_prototype_summary.csv", index=False)

    order = (
        long_df.groupby("prototype_id", observed=True)["neural_residual_after_velocity_distance"]
        .median().sort_values().index
    )
    data_to_plot = [
        long_df.loc[
            long_df["prototype_id"] == proto,
            "neural_residual_after_velocity_distance",
        ].values
        for proto in order
    ]
    plt.figure(figsize=(8, 4))
    plt.boxplot(data_to_plot, labels=[str(x) for x in order], showfliers=False)
    plt.axhline(0, linestyle="--", linewidth=1)
    plt.xlabel("LISBET/HMM prototype ID")
    plt.ylabel("Neural residual after velocity + distance")
    plt.title("Residual VTA neural activity by LISBET prototype")
    plt.tight_layout()
    plt.savefig(outdir / "residual_neural_activity_by_lisbet_prototype.png", dpi=600)
    plt.close()

    summary_path = outdir / "analysis_summary.txt"
    with summary_path.open("w") as f:
        f.write("VTA LISBET analysis summary\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"Input: {long_csv}\n")
        f.write(f"Long event-neuron observations: {len(long_df)}\n")
        f.write(f"Units: {long_df['unit_id'].nunique()}\n")
        f.write(f"Trials in model: {long_df['trial_id'].nunique()}\n")
        f.write(f"Prototypes in model: {long_df['prototype_id'].nunique()}\n\n")
        f.write("Model comparison:\n")
        f.write(comparison.T.to_string())
        f.write("\n\nResidual analysis:\n")
        f.write(resid_comparison.T.to_string())
        f.write("\n\nResidual by prototype:\n")
        f.write(resid_summary.to_string(index=False))
        f.write("\n")

    print(comparison.T)
    print("Saved outputs to:", outdir)


if __name__ == "__main__":
    main()
